### ISSUE TITLE
Issue with RC tag names

### ISSUE THREAD

**Issue by Joebayld** [LiveUI/S3#16]
I may be wrong here - but why are all the tag names so inconsistent? 

v3.0.0-rc2
3.0.0-RC3.0.1 
3.0.0-RC3
3.0.0-RC2

Swift package manager doesn't like this.. I also don't think "v" should not be in the tag name either. rc2 shouldn't come after RC3.0.1. Thoughts?

For now, I'm just forking it and releasing a tag that works for swift PM.

**Comment by rafiki270** [comment]
sorry :) ... fixed

**Comment by Joebayld** [comment]
Thanks!
Also, I think the amount of digits should also be consistent moving forward. Example: 

3.0.0-RC3.1.1 should never come after 3.0.0-RC3.1. So support 3 version numbers, it would be 3.0.0-RC3.1.0. But this works for now.
