### ISSUE TITLE
`get` and `delete` cache issue?

### ISSUE THREAD

**Issue by zdnk** [LiveUI/S3#19]
I am working on file management abstraction for Swift and Vapor 3 and I have found probably a bug in cache/header management.

On getting file and immediately after that trying to delete it or even after running it second time, I get on `get` or `delete` this:

>  errorResponse(NIOHTTP1.HTTPResponseStatus.notImplemented, S3.ErrorMessage(code: "NotImplemented", message: "A header you provided implies functionality that is not implemented", bucket: nil, endpoint: nil, header: Optional("If-Modified-Since"), requestId: Optional("69D5F968DFC541E3"), hostId: Optional("MpD4rDbYQxpw5gOzln5q3mOlTEhmW8kqVCx+5bk9+JOyx26bOv2IznWqwN554TEWwqMvQ+eu/5k=")))

You can see by pulling the project, fetching deps and running tests: https://github.com/zdnk/vapor-filesystem/tree/4f6187b1c8d7306e78c1dbb5d74d752acf0c97db
Commit: 4f6187b1c8d7306e78c1dbb5d74d752acf0c97db

I am using there the latest RC of version 3 as you can see in Package files.

**Comment by rafiki270** [comment]
I already got one of them through here 
https://github.com/vapor/vapor/pulls?q=is%3Apr+is%3Aclosed+author%3Arafiki270

Unfortunately the one which alows for custom configuration didn’t make it through

**Comment by zdnk** [comment]
@rafiki270 is there anything we can do to speed this up? it is half a year already. Or simply use workaround? (directly using `URLSession`) instead of `FoundationClient`

**Comment by rafiki270** [comment]
tbh, if we use URLSession (and move one of the crypto methods out) we might be able to get rid of the vapor dependency all together ...

**Comment by zdnk** [comment]
Perfect! I totally vote with all my 10 fingers for this. Suddenly you can have framework-agnostic server-side Swift S3 package. With more changes (using blocks instead of Futures) you can even have iOS package and do NIO futures as extension only with separate package :)

**Comment by rafiki270** [comment]
:)
I would still like to keep the NIO Futures for compatibility

**Comment by zdnk** [comment]
Well if you release just this fix, then yes, if you make a breaking change, then it can make sense, but I understand, the goal is server-side (Vapor) for now. So are you ok If I open PR for removing the `Vapor.Client` dependency and use `URLSession` directly?

**Comment by rafiki270** [comment]
yeah man

**Comment by zdnk** [comment]
Ok cool. Ill keep dependency on `Vapor.Container` for now for backward compatibility.

**Comment by zdnk** [comment]
PR created, hopefully, you guys will be able to review it, merge it and release a new version soon.

**Comment by iGranDav** [comment]
Since the last PR is merged, you should probably close this issue?

**Comment by rafiki270** [comment]
yes, thanks @iGranDav :)
