### ISSUE TITLE
XAmzContentSHA256Mismatch

### ISSUE THREAD

**Issue by SmartJSONEditor** [LiveUI/S3#47]
Hello, I am not sure what happend but after some time this library was working fine, I am starting getting issues on linux. This issues do not happen when compiled on macOS local machine, just getting them when running in Ubuntu 18.04

errorResponse(NIOHTTP1.HTTPResponseStatus.badRequest, S3.ErrorMessage(code: "XAmzContentSHA256Mismatch", message: "The provided \'x-amz-content-sha256\' header does not match what was computed.", bucket: nil, endpoint: nil

**Comment by SmartJSONEditor** [comment]
This issue happens when Vapor receives a file data via post request. This issue do not happen when you load a local file and send it to amazon, only when the data is received via post data.

**Comment by juanLovera** [comment]
Until there's a final bug fix for this you can put this in the headers to make it work: ["x-amz-content-sha256": "UNSIGNED-PAYLOAD"]

**Comment by vegiwoo** [comment]
Good afternoon, did you somehow solve this problem? Everything works fine for me on the local mac, on a remote server with Ubuntu I get this problem

**Comment by juanLovera** [comment]
Yes, instead of directly uploading the file received through the multipart,
create an intermediate one:

let file = File.Upload(data: Data(imageRequest.file.data.withByteBuffer {
$0 }), bucket: defaultBucket, destination: destination, access: .publicRead)

            return try s3.put(file: file, headers: [:], on: req)
