### ISSUE TITLE
Status: 307

### ISSUE THREAD

**Issue by sergeymild** [LiveUI/S3#5]
When i am trying upload file like: 
```try s3.put(bytes: bytes, filePath: "example/example.txt")```
i always get an error S3.Error: badResponse 307.

**Comment by emilpedersen** [comment]
I get the same error

**Comment by at-tuanmai2** [comment]
I get the same error

**Comment by rafiki270** [comment]
vapor 3 package has been released and I am unfortunately unable to support the 2.0 version anymore. Please feel tree to create a PR for the 2.0 branch if you'd like and I am happy to look at it. I think the problem is with an incorrect URL format for the S3 client.
