### ISSUE TITLE
Custom S3 url

### ISSUE THREAD

**Issue by joscdk** [LiveUI/S3#6]
Is it possible to use a custom S3 URL, to use it with different S3 compatible storage providers e.g. Digital Ocean Spaces or self hosted Minio/CephFS?

**Comment by rafiki270** [comment]
with a small modification it would be, can you give me an example?

**Comment by rafiki270** [comment]
@joscdk

**Comment by rafiki270** [comment]
URLBuilder has been protocolised so potentially any compatible service should be available if you inject a custom builder
