### ISSUE TITLE
Deploying to linux issue

### ISSUE THREAD

**Issue by Prince2k3** [LiveUI/S3#8]
```
error: cannot convert value of type 'NSMutableCharacterSet' to type 'CharacterSet' in coercion
return self.addingPercentEncoding(withAllowedCharacters: allowed as CharacterSet)
```

I experience this is when trying to deploy to remote via heroku

**Comment by rafiki270** [comment]
Thanks! I’ll look into it tonight! I have only testing this on docker so far

**Comment by rafiki270** [comment]
@Prince2k3 could you please check again against master?

**Comment by rafiki270** [comment]
fixed on master
